apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app-container
        image: java123456.azurecr.io/project:${{ github.sha }}
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret
