apiVersion: v1
kind: Service
metadata:
  name: my-app-deployment
  labels:
    app: my-app-deployment
spec:
  selector:
    app: my-app-deployment
  ports:
    - port: 8080
      targetPort: 8080
  type: LoadBalancer
