name: Java CI with Maven

permissions:
  id-token: write
  contents: read 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  AZURE_CONTAINER_REGISTRY: "java123456"
  CONTAINER_NAME: "project"
  RESOURCE_GROUP: "example1"
  AKS_CLUSTER_NAME: "new-cluster"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload WAR file
      uses: actions/upload-artifact@v4
      with:
        name: war-file 
        path: /home/runner/work/project-maven/project-maven/webapp/target/*.war

    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build Docker image
      run: docker build -t ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest .

    - name: Push Docker image to ACR
      run: docker push ${{ env.AZURE_CONTAINER_REGISTRY }}.azurecr.io/${{ env.CONTAINER_NAME }}:latest

    - name: Set AKS context
      uses: azure/aks-set-context@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        cluster-name: ${{ env.AKS_CLUSTER_NAME }}
        resource-group: ${{ env.RESOURCE_GROUP }}

    - name: Deploy to AKS
      run: |
        kubectl apply -f webapp/deployment.yml
        kubectl apply -f webapp/service.yml
