name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Upload .war file
      uses: actions/upload-artifact@v3
      with:
        name: my-war-file
        path: /home/runner/work/project-maven/project-maven/webapp/target/*.war

    - name: Azure login
      uses: azure/login@v1.4.6
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:latest

    - name: Push the Docker image
      run: docker push ${{ secrets.REGISTRY_NAME }}.azurecr.io/my-app:${{ github.sha }} 

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
